INSERT INTO product (id, name, keywords, description) VALUES
    (1,  'Interior matt paint',      'paint, interior paint, wall, living room',                     'Hard-wearing white matt emulsion for refreshing interior walls and ceilings.'),
    (2,  'Paint roller set',         'paint, roller, paint rollers, walls, paint tray, paint trays', 'Rollers and a paint tray for applying an even finish to large wall areas.'),
    (3,  'Wall filler',              'fill, repair, crack, wall',                                    'Ready-mixed filler for repairing small cracks, dents and holes in interior walls.'),
    (4,  'Wood screws',              'screw, wood, fixings',                                         'Multipurpose screws for joining timber and completing indoor woodwork projects.'),
    (5,  'Cordless drill',           'drill, hole, wood, wall',                                      'Compact cordless drill for drilling pilot holes and assembling everyday home projects.'),
    (6,  'Paint brush set',          'paint, brush, paint brushes, trim',                            'Set of three brushes for cutting in around edges, trim and detailed areas.'),
    (7,  'Painter''s tape',          'paint, masking, masking tape, edges',                          'Low-tack masking tape that protects trim and leaves crisp paint lines.'),
    (8,  'Dust sheet',               'paint, decorating, protect, drop cloth, drop cloths',          'Reusable cotton dust sheet for shielding floors and furniture while decorating.'),
    (9,  'Sandpaper pack',           'sand, smooth, wood, wall',                                     'Assorted-grit sandpaper sheets for smoothing timber and preparing filled walls.'),
    (10, 'Wood glue',                'glue, wood, repair',                                           'Fast-setting wood adhesive for bonding and repairing interior timber joints.'),
    (11, 'Pine timber board',        'wood, timber, shelf',                                          'Planed pine board for making shelves, simple storage and other small projects.'),
    (12, 'Shelf brackets',           'shelf, bracket, storage',                                      'Pair of sturdy steel brackets for supporting a wall-mounted shelf.'),
    (13, 'Spirit level',             'level, measure, wall',                                         'Compact spirit level for aligning shelves, frames and other wall-mounted items.'),
    (14, 'Claw hammer',              'hammer, nail, fixing',                                         'General-purpose claw hammer for driving or removing nails during household repairs.'),
    (15, 'Masonry drill bits',       'drill, masonry, brick, wall',                                  'Set of masonry bits for drilling clean holes in brick, blockwork and concrete.'),
    (16, 'Wall plugs',               'wall, fixing, screw, brick',                                   'Assorted wall plugs for securing screws in brick, masonry and plasterboard.'),
    (17, 'Adjustable spanner',       'spanner, plumbing, nut',                                       'Adjustable spanner for tightening or loosening nuts on common plumbing fittings.'),
    (18, 'PTFE tape',                'plumbing, leak, thread',                                       'Thread-sealing tape for creating watertight connections on threaded pipe fittings.'),
    (19, 'Silicone sealant',         'seal, bathroom, kitchen',                                      'White waterproof silicone sealant for sealing gaps around baths, sinks and worktops.'),
    (20, 'LED light bulb',           'light, bulb, electrical',                                      'Warm-white, energy-efficient LED bulb with a standard bayonet-cap fitting.'),
    (21, 'Extension lead',           'electrical, power, cable',                                     'Four-socket extension lead for safely powering indoor tools and appliances.'),
    (22, 'Work gloves',              'gloves, safety, garden',                                       'Durable work gloves that protect hands during DIY tasks and light gardening.'),
    (23, 'Safety goggles',           'goggles, safety, drill',                                       'Clear safety goggles for protecting eyes from dust and debris while drilling or sanding.'),
    (24, 'Garden trowel',            'garden, soil, planting',                                       'Hand trowel for digging small holes, planting seedlings and potting plants.'),
    (25, 'Compost bag',              'garden, compost, soil',                                        'Peat-free compost for filling containers, potting plants and raised beds.'),
    (26, 'Interior wall primer',     'primer, wall primer, interior primer',                         'Water-based primer that seals and prepares interior walls for a smooth paint finish.'),
    (27, 'Garden fork',              'garden, fork, soil, digging, turning soil',                    'Sturdy garden fork for loosening compacted soil, turning compost and lifting plants.'),
    (28, 'Digging spade',            'garden, spade, digging, soil, edging',                         'Steel digging spade for digging borders, moving soil and cutting clean lawn edges.'),
    (29, 'Garden rake',              'garden, rake, leaves, soil, levelling',                        'Wide-headed rake for collecting leaves and levelling soil before sowing seeds.'),
    (30, 'Secateurs',                'garden, secateurs, pruning, pruning shears, cutting',          'Bypass secateurs for pruning stems, deadheading flowers and cutting back shrubs.'),
    (31, 'Hedge shears',             'garden, hedge, shears, pruning, trimming',                     'Long-handled hedge shears for shaping hedges and trimming overgrown shrubs.'),
    (32, 'Garden hose',              'garden, hose, watering, water',                                'Fifteen-metre flexible garden hose for watering beds, containers and lawns.'),
    (33, 'Hose spray gun',           'garden, hose, spray gun, watering, nozzle',                    'Adjustable spray gun with jet, mist and shower settings for controlled watering.'),
    (34, 'Watering can',             'garden, watering can, water, plants',                          'Ten-litre watering can with a removable rose for watering flowers and vegetable beds.'),
    (35, 'Lawn mower',               'garden, lawn mower, grass, cutting, lawn',                     'Electric rotary lawn mower for maintaining small and medium-sized lawns.'),
    (36, 'Grass trimmer',            'garden, grass trimmer, strimmer, lawn edges, weeds',           'Cordless grass trimmer for tidying lawn edges and cutting grass around obstacles.'),
    (37, 'Wheelbarrow',              'garden, wheelbarrow, soil, compost, transport',                'Galvanised wheelbarrow for moving soil, compost, plants and garden waste.'),
    (38, 'Garden kneeler',           'garden, kneeler, knee pads, planting, weeding',                'Foam garden kneeler that protects knees while planting, weeding and tending beds.'),
    (39, 'Plant support canes',      'garden, canes, plant support, bamboo, staking',                'Bamboo canes for supporting climbing plants, tomatoes and young shrubs.'),
    (40, 'Weed killer',              'garden, weed killer, weeds, lawn, paths',                      'Ready-to-use weed killer for treating unwanted growth on paths, patios and borders.'),
    (41, 'Laminate flooring',        'flooring, laminate, floor, wood effect, planks',               'Durable oak-effect laminate planks for updating living rooms, bedrooms and hallways.'),
    (42, 'Vinyl floor tiles',        'flooring, vinyl, floor tiles, kitchen, bathroom',              'Water-resistant vinyl tiles for practical kitchen, bathroom and utility-room floors.'),
    (43, 'Underlay roll',            'flooring, underlay, laminate, insulation, soundproofing',      'Foam underlay that cushions laminate flooring and helps reduce sound between rooms.'),
    (44, 'Flooring adhesive',        'flooring, adhesive, glue, vinyl, floor tiles',                 'High-grab adhesive for securing vinyl flooring and tiles to a prepared subfloor.'),
    (45, 'Floor levelling compound', 'flooring, levelling compound, screed, subfloor, repair',       'Self-levelling compound for smoothing uneven subfloors before laying new flooring.'),
    (46, 'Door threshold strip',     'flooring, threshold, transition, door bar, edging',            'Aluminium threshold strip for creating a neat transition between adjoining floors.'),
    (47, 'Skirting board',           'flooring, skirting, trim, wall, finishing',                    'Primed MDF skirting board for finishing the edge where a new floor meets the wall.'),
    (48, 'Laminate cutter',          'flooring, laminate cutter, cutting, planks, tool',             'Manual laminate cutter for making clean, dust-free cuts in flooring planks.'),
    (49, 'Flooring pull bar',        'flooring, pull bar, laminate, fitting, installation',          'Steel pull bar for drawing the final laminate boards tightly into position.'),
    (50, 'Flooring tapping block',   'flooring, tapping block, laminate, fitting, installation',     'Impact-resistant tapping block for joining laminate planks without damaging edges.'),
    (51, 'Flooring spacers',         'flooring, spacers, laminate, expansion gap, fitting',          'Reusable spacers for maintaining the required expansion gap around a floating floor.'),
    (52, 'Knee pads',                'flooring, knee pads, protection, fitting, tiling',             'Cushioned knee pads for comfortable protection while laying floors or tiles.'),
    (53, 'Notched adhesive trowel',  'flooring, trowel, adhesive, tile, vinyl',                      'Notched trowel for spreading an even bed of adhesive when fitting tiles or vinyl flooring.'),
    (54, 'Floor scraper',            'flooring, scraper, adhesive, subfloor, preparation',           'Heavy-duty floor scraper for removing old adhesive, residue and loose floor coverings.');
